import "./globals.css";
import { Inter } from "next/font/google";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          "overflow-x-hidden overscroll-none w-full h-full"
        )}
      >
        {children}
      </body>
    </html>
  );
}
