import "./globals.css";
import { Inter, Oswald } from "next/font/google";
import classNames from "classnames";
import { Toaster } from "react-hot-toast";
import { SWRProvider } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "CRUD City",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        id="#next"
        className={classNames(
          inter.className,
          oswald.className,
          "overflow-x-hidden overscroll-none w-full h-full font-body"
        )}
      >
        <SWRProvider>
          <Toaster
            position="bottom-center"
            containerStyle={{
              top: 40,
              left: 40,
              bottom: 40,
              right: 40,
            }}
            toastOptions={{
              duration: 5000,
              className:
                "max-w-[200px] font-body text-white rounded-md shadow-md p-3",
              style: {
                background: "#3c3744",
                color: "#fff",
              },
            }}
          />
          {children}
        </SWRProvider>
      </body>
    </html>
  );
}
